### ISSUE TITLE
row'un gerekliliği hk.

### ISSUE THREAD

**Issue by vemeoy** [yelbuke/VeMEY#2]
cabinete'e isim verirken zaten rowun ismi tekrarlanıyor gibi. A rowu, A1 kabineti şeklinde. kabinet isimlerini 1,2,3 yaparsan da , A, B, C rowlarında birer tane 1 kabineti olur. Sanki bu Row modeli gereksiz.

**Comment by yelbuke** [comment]
O halde row'u kaldıralım. İsteyen kabinetleri A00-A01-A02 diye isimlendirerek konuyu hallederler.

**Comment by vemeoy** [comment]
DCnin haritasi falan elimizde olmadikca, ve kabinetler arasi mesafeler, ve fiziksel iliskileri koymadikca row isimize ne kadar yarar emin degilim. Ha kullanmaya devam ederiz ama cihaz isimlendirmelerinde gizli tutariz vs.

**Comment by vemeoy** [comment]
Ileriki fazlara DC kabinet yerlesimi plani falan koyulabikirse o zaman daha anlamli olacaktir.

**Comment by yelbuke** [comment]
o vakit ekleriz o halde row'u.
