### ISSUE TITLE
Device ordering

### ISSUE THREAD

**Issue by vemeoy** [yelbuke/VeMEY#3]
Device :
Class meta:
      ordering = device.rackunit.no   olacak sanirim. Boyle yapalim.

**Comment by yelbuke** [comment]
device'ın birden fazla rackunit'i olduğunda hangi rackunit'in nosuna göre ordering yapacak? rackunit'in manytomany olarak tanımlanmış olması sıkıntı yaratabilir.

**Comment by vemeoy** [comment]
Rackunit.no.__minimum__ olmaz mi?

**Comment by yelbuke** [comment]
Bilmem. o şekilde veya başka şekilde belirtilebiliyorsa olur tabii.

2015-12-08 3:43 GMT-08:00 vemeoy <notifications@github.com>:

**Comment by vemeoy** [comment]
Simdilik rack e gore listeliyoruz.
