### ISSUE TITLE
Ana menüdeki bazı öğelerin gruplandırılması

### ISSUE THREAD

**Issue by yelbuke** [yelbuke/VeMEY#4]
Ana menüdeki "companies", "countries", "cities" ve "buildings" ögelerinin belirlenen bir başlık altında gruplanması.

**Comment by yelbuke** [comment]
Hangi başlık altında gruplamalıyız?

**Comment by vemeoy** [comment]
Settings diyelim gecelim. Port types, device types i da atalim altina

**Comment by yelbuke** [comment]
gerekli duzenlemeler yapıldı.
